#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

decomposePar

# Get application name from directory
compileLibrary myRBFMotionFunction


mpirun -np 32 icoDyMFoam -parallel >log

